### ISSUE TITLE
vlcj play h264 camera stream

### ISSUE THREAD

**Issue by cszczotka** [caprica/vlcj#420]
Hi,
I'm using vlcj to play h264 camera stream (available over http) in simple java gui application. My issue is that after few sconds of playing the stream is broken and whole screen (EmbeddedMediaPlayerComponent) make  grey. This repeats again and again. In java output I see such error when playing is broken:

[00000000002bd700] core input error: ES_OUT_SET_(GROUP_)PCR  is called too late (pts_delay increased to 1854 ms)
[00000000002bd700] core input error: ES_OUT_RESET_PCR called
[00000000002bd700] core input error: ES_OUT_SET_(GROUP_)PCR  is called too late (pts_delay increased to 2548 ms)
[00000000002bd700] core input error: ES_OUT_RESET_PCR called
[00000000002bd700] core input error: ES_OUT_SET_(GROUP_)PCR  is called too late (pts_delay increased to 4242 ms)
[00000000002bd700] core input error: ES_OUT_RESET_PCR called

Currently I have set only one option in MediaPlayer  :demux=h264

Maybe I lose same MadiaPlayer option like frame rate?

My OS is Windows 7 64 bit, java8 64 bit.  VLC media player - 2.2.1.

**Comment by caprica** [comment]
Impossible to say with what little you've posted here.

Maybe your CPU can't decode the stream quickly enough.

Maybe there's a problem in your Java code.

I've played such streams before without problems, so you're going to have to provide some more useful info if you want help.

**Comment by cszczotka** [comment]
Hi,
Thanks for response.
I don't think so that it is slow CPU. I have quite powerful workstation and I don't see under task manager that CPU is busy.

Below is my demo java code:


public class Demo {

    private static final String VLC_HOME = "c:/Program Files/VideoLAN/VLC";

    public static void main(String... args) {

        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                Demo demo = new Demo();
                demo.start("http://some_stream_url");

            }
        });
    }

    public void start(String streamUrl) {
        initVlc();
        startApp(streamUrl);
    }

    void initVlc() {
        NativeLibrary.addSearchPath(RuntimeUtil.getLibVlcLibraryName(), VLC_HOME);
        String libName = RuntimeUtil.getLibVlcLibraryName();
        Native.loadLibrary(libName, LibVlc.class);
    }

    void startApp(String streamUrl) {
        JFrame frame = new JFrame("H264 demo");
        JPanel contentPanel = new JPanel();
        contentPanel.setLayout(new BorderLayout());
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setLocation(100, 100);
        frame.setSize(1024, 768);

        EmbeddedMediaPlayerComponent mediaPlayerComponent = new EmbeddedMediaPlayerComponent();
        contentPanel.add(mediaPlayerComponent, BorderLayout.CENTER);
        frame.setContentPane(contentPanel);



        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);


        mediaPlayerComponent.getMediaPlayer().playMedia(streamUrl, new String[]{":demux=h264"});
    }
    
}

**Comment by caprica** [comment]
So are you sure your media player instance is not going out of scope and being garbage collected some time after your startApp method returns?

Also, isn't dmux=h264 by itself a bit unusual, it usually goes with other options like bitrate doesn't it.

**Comment by cszczotka** [comment]
Hi,
Ok. I fixed now EmbeddedMediaPlayerComponent mediaPlayerComponent is a attribute in class Demo.
So in VLC I have to set Demux module on "h264 video demuxer" to play this h264 stream. (see on attached screen)
![demuxer](https://cloud.githubusercontent.com/assets/1387823/10893183/b66d5eb8-81a7-11e5-881e-f710726a17e5.png)

Do you have any example of options which allow me play h264 stream ?
Thanks,

**Comment by caprica** [comment]
OK, but I guess that did not actually fix your problem with the stream stopping?

I'm not even sure passing ":demux=h264" as a media option when you play the media is possible.

Maybe try {"--demux", "h264"} when you create the media player factory. I'm really not sure, this is outside the scope of vlcj really.

**Comment by cszczotka** [comment]
Ok. I will try. One more question. What options you are using during vlcj tests with h264 streams ? I have browsed code of vlcj but I don't see any test for such scenario. Do you have something ?

**Comment by caprica** [comment]
I have been looking for the sample code, I can't find it.

I don't recall ever setting mux=h264 explicitly.

Either that, or I'm an inadvertent liar and I'm confusing this issue with some other issue with h264 streaming, sorry I really can't remember at the moment.

**Comment by cszczotka** [comment]
Hi,
I have found such tip: https://bbs.archlinux.org/viewtopic.php?id=170463

So I have downgraded vlc to 2.0.8 and vlcj to 2.2.0 and I don't see error : "core input error: ES_OUT_SET_(GROUP_)PCR is called too late..."
Also player screen is not broken ( grey ).
Do you know what is the newest version of vlcj which works with vlc 2.0.8 ?

**Comment by caprica** [comment]
Probably 2.4.1.
